# Generated by Django 2.2.2 on 2019-06-05 18:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Имя врача', max_length=128)),
                ('last_name', models.CharField(help_text='Фамилия врача', max_length=128)),
                ('specialization', models.CharField(help_text='Специализация врача', max_length=64)),
                ('start_work_time', models.TimeField(help_text='Время начала приема')),
                ('end_work_time', models.TimeField(help_text='Время окончания приема')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Время и дата записи')),
                ('pacient_fio', models.CharField(help_text='ФИО пациента', max_length=128)),
                ('to_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Doctor')),
            ],
            options={
                'verbose_name': 'Прием',
                'verbose_name_plural': 'Приемы',
                'ordering': ['date'],
            },
        ),
    ]
